export const constRoute = {
  // dashboard: "/",
  dashboard: "/",
  // commingSoon: "",
  hash: "#",
  login: "/login",
  aboutUs: "/about-us",
  selfExclusionPolicy: "/self-exclusion-policy",
  KYC: "/KYC",
  finalSheet: "/final-sheet",
  finalSheet2: "/final-sheet-2",
  dailyReport: "/daily-report",
  dailyPl: "/daily-pl",
  bookDetail: "/book-detail",
  profile: "/profile",
  setting: "/setting",
  fakeBets: "/fake-bets",
  viewFakeBet: "/view-fake-bets",
  loadBalance: "/load-balance-form",
  users: "/users",
  userBetForm: "/user-bet-form",
  recharges: "/recharges",
  allCasino: "/all-casino",
  cricket: "/cricket",
  betLocker: "/bet-lock",
  horseRace: "/horse-race",
  greyhound: "/greyhound",
  soccer: "/soccer",
  tennis: "/tennis",
  kabaddi: "/kabaddi",
  iceHockey: "/ice-hockey",
  snooker: "/snooker",
  royalStarCasino: "/royal-star-casino",
  starCasino: "/star-casino",
  royalCasino: "/royal-casino",
  betFairGames: "/betfair-games",
  betFairGamesDetail: "/bet-fair-games-detail",
  currentPosition: "/current-positions",
  allSports: "/all-sports",
  results: "/results",
  result: "/result",
  marketRules: "/market-rules",
  termsAndConditions: "/terms-and-conditions",
  cash: "/cash",
  ledger: "/ledger",
  betsList: "/bets-list",
  customerBetList: "/customer/bets-list",
  creditLedger: "/credit-ledger",
  ledgerReport: "/ledger-report",
  ledgerCash: "/ledgerCash",
  ledgerCredit: "/ledgerCredit",

  ledgerTwo: "/ledger-two",
  profiltLoss: "/profit-loss",
  customerProfitLoss: "/customer/profit-loss",
  privacyPolicy: "/privacyPolicy",
  sideBarCurrentPosition: '/market/liables',
  commissionReport: '/commission',
  bookDetail2: "/book-detail2",
  casinos: "/all-world-casino",
  relatedGame: '/related-games',
  casinoGames: "/casino-games",
  evolutionCasino: "/evolution-casino",
  ezugicasino: "/ezugi-casino",
  casino: "/casino",
  reports:"/reports",
  dashboardGame: "/dashboard-games",
  reportByMarket: "/report-by-market",
  reportMarketShare: '/Reports/MarketShares',
  dailyReportMarketShare:"/daily-pl/MarketShares",
  settlement: '/settlement',
  accountStatement: '/account/statement',
  betterResults: '/customer/results',
  digitRate: '/digitRate',
  fullBetList: '/fullBetList',
  responsibleGame: '/responsible-game',
  disputeResoultion: '/dispute',
  accountBalance: '/A-P-B',
  rulesRegulation:'/rules-regulation',
  underAgePolicy:'/under-age-policy',
  aml:'/aml',
  fairnessAndRNG: '/fairness-and-rng',
  sportsBook: '/sports-book',
  userBook: '/user-book',
  userBookSoccer: '/soccer-user-book',
  userBookHorse: '/horse-user-book',
  userBookGreyHound: '/grey-hound-user-book',
  userBookCricket: '/cricket-hound-user-book',
  matchSettlement: 'match-settlement',
  loginUser: '/login-users',
  profitLossDetail: 'profit-loss-detail',
  loginHistory: '/login-history',
  bookDetailedport: '/book-report/detail',
  asianGames: '/asian-games',
  activeBets: '/active-bets',
  allBettors: '/all-bettors',
  statement: '/statement',
  statementDetail: '/statement-detail',
  asianGame: '/asian-games',
  oneOBetCasinoDash: "/one-o-bet-casino-dashboard",
  oneOBetCasino:'/oneobet-casino',
  cricketMarketWise:'/cricket-market-wise',
  soccerMarketWise: '/soccer-market-wise',
  cricketMatch: '/cricket-match',
  soccerMatch: '/soccer-match',
  tennisMatch: '/tennis-match',
  openMarkets: '/open-markets',
  fancyListings: '/fancy-listings',
  sportsHighlight: '/sports-highlight',
  casinoListings: '/casino-listings',
};